services:
  app:
    build: .
    container_name: hello-app
    depends_on:
      - redis
    ports:
      - "8002:8001"
    environment:
      REDIS: redis:6379

  redis:
    image: redis:latest
    container_name: redis-db
